#!/bin/bash

#Make scripts usable
chmod +x /usr/local/bin/portenable
chmod +x /usr/local/bin/portdisable
chmod +x /usr/local/bin/scan
chmod +x /usr/local/bin/networkactive
chmod +x /usr/local/bin/createuser



#Execute config files
bash /etc/server-config/config_clamav.sh
bash /etc/server-config/config_ufw.sh
bash /etc/server-config/install_ssh.sh
bash /etc/server-config/rules_snort.sh