#!/bin/bash

# Make scripts executable
chmod +x /usr/local/bin/ufwenable
chmod +x /usr/local/bin/ufwdisable

# Execute Snort configuration
bash /etc/my-ufw-tools/snort-rules.sh

# Execute UFW configuration
bash /etc/my-ufw-tools/ufw-config.sh